import { z } from "zod";
import {
  saveTranscriptToDb,
  type TranscriptResult,
} from "@/db/save-transcript";

// ============================================================================
// Zod schema for validating Apify API response (snake_case as returned by API)
// ============================================================================

const TranscriptSegmentSchema = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
});

const ApifyTranscriptResponseSchema = z.object({
  video_id: z.string(),
  url: z.string(),
  title: z.string(),
  published_at: z.string(),
  channel_id: z.string(),
  channel_name: z.string(),
  description: z.string(),
  subscriber_count: z.number(),
  view_count: z.number(),
  like_count: z.number(),
  duration_seconds: z.number(),
  is_auto_generated: z.boolean(),
  thumbnail: z.string(),
  transcript: z.array(TranscriptSegmentSchema),
});

// ============================================================================
// Transform snake_case API response to camelCase internal format
// ============================================================================

function transformApifyResponse(
  data: z.infer<typeof ApifyTranscriptResponseSchema>,
): TranscriptResult {
  return {
    videoId: data.video_id,
    url: data.url,
    title: data.title,
    date: data.published_at,
    channelId: data.channel_id,
    channelName: data.channel_name,
    description: data.description,
    numberOfSubscribers: data.subscriber_count,
    viewCount: data.view_count,
    likes: data.like_count,
    duration: formatDurationFromSeconds(data.duration_seconds),
    isAutoGenerated: data.is_auto_generated,
    thumbnailUrl: data.thumbnail,
    transcript: data.transcript,
  };
}

// Convert seconds to duration string (e.g., "50:20" or "1:23:45")
function formatDurationFromSeconds(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

// ============================================================================
// Step: Start Apify Extraction
// ============================================================================

export async function startApifyTranscriptExtraction(
  videoId: string,
): Promise<{ runId: string; defaultDatasetId: string }> {
  "use step";

  const { ApifyClient } = await import("apify-client");

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });
  const actorRun = await client.actor("Uwpce1RSXlrzF6WBA").start({
    youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
  });

  return { runId: actorRun.id, defaultDatasetId: actorRun.defaultDatasetId };
}

// ============================================================================
// Step: Check Apify Status
// ============================================================================

export async function checkApifyExtractionStatus(
  runId: string,
): Promise<{ status: string }> {
  "use step";

  const { ApifyClient } = await import("apify-client");

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });
  const run = await client.run(runId).get();

  if (!run) {
    throw new Error(`Apify run ${runId} not found`);
  }

  return { status: run.status };
}

// ============================================================================
// Step: Fetch and Save (Combined)
// ============================================================================

export async function fetchAndSaveApifyTranscript(
  runId: string,
  datasetId: string,
): Promise<{ success: true; videoId: string }> {
  "use step";

  const { ApifyClient } = await import("apify-client");

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });

  // Get items from dataset
  const { items } = await client.dataset(datasetId).listItems();
  const rawApiResponse = items[0];

  if (!rawApiResponse) {
    throw new Error(`No results found in dataset: ${datasetId}`);
  }

  // Validate the API response with Zod
  const parseResult = ApifyTranscriptResponseSchema.safeParse(rawApiResponse);

  if (!parseResult.success) {
    console.error(
      "[Apify] Validation failed. Raw response keys:",
      Object.keys(rawApiResponse),
    );
    console.error(
      "[Apify] Validation errors:",
      JSON.stringify(parseResult.error.format(), null, 2),
    );
    throw new Error(
      `Invalid Apify response: ${parseResult.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join(", ")}`,
    );
  }

  // Transform snake_case API response to camelCase
  const transcriptData = transformApifyResponse(parseResult.data);

  // Save to DB
  await saveTranscriptToDb(transcriptData);

  return { success: true, videoId: transcriptData.videoId };
}

// Legacy function (kept for now, but will be removed or updated)
export async function fetchYoutubeTranscriptFromApify(
  _videoId: string,
): Promise<TranscriptResult> {
  // I'll leave this for now and remove it after updating consumers
  // Actually, I'll remove it in the same overwrite since I'm rewriting the file.
  throw new Error("Deprecated");
}
export async function saveYoutubeTranscriptToDb(data: TranscriptResult) {
  await saveTranscriptToDb(data);
}
