#!/usr/bin/env tsx

/**
 * CLI script to test the fetch transcript functionality
 * Usage: npm run test-transcript <videoId> [--save-to-db]
 * Example: npm run test-transcript dQw4w9WgXcQ
 * Example: npm run test-transcript dQw4w9WgXcQ --save-to-db
 */

import { ApifyClient } from "apify-client";
import 'dontenv/config'
import {
  saveTranscriptToDb,
  type TranscriptResult,
} from "../db/save-transcript";

async function fetchTranscriptFromApify(
  videoId: string,
): Promise<TranscriptResult | null> {
  if (!process.env.APIFY_API_TOKEN) {
    throw new Error(
      "APIFY_API_TOKEN is not defined. Please set it in your .env.local file",
    );
  }

  console.log(`\n🔍 Fetching transcript for video ID: ${videoId}`);
  console.log(`📡 Using Apify API...\n`);

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });

  try {
    const run = await client.actor("Uwpce1RSXlrzF6WBA").call({
      youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
    });

    console.log(`✅ Apify run completed: ${run.id}`);

    const { items } = await client.dataset(run.defaultDatasetId).listItems();
    return (items[0] as unknown as TranscriptResult | undefined) ?? null;
  } catch (error) {
    console.error("❌ Error fetching transcript:", error);
    throw error;
  }
}

function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function displayResults(result: TranscriptResult) {
  console.log("\n📊 RESULTS:");
  console.log("━".repeat(80));
  console.log(`\n📹 Video Information:`);
  console.log(`   ID: ${result.id}`);
  console.log(`   Title: ${result.title}`);
  console.log(`   URL: ${result.url}`);
  console.log(`   Channel: ${result.channelName} (${result.channelId})`);
  console.log(`   Published: ${result.date}`);
  console.log(`   Duration: ${result.duration}`);
  console.log(`   Views: ${result.viewCount.toLocaleString()}`);
  console.log(`   Likes: ${result.likes.toLocaleString()}`);
  console.log(`   Subscribers: ${result.numberOfSubscribers.toLocaleString()}`);
  console.log(`   Auto-generated: ${result.isAutoGenerated ? "Yes" : "No"}`);

  if (result.description) {
    console.log(`\n📝 Description:`);
    console.log(
      `   ${result.description.substring(0, 200)}${result.description.length > 200 ? "..." : ""}`,
    );
  }

  if (result.transcript && result.transcript.length > 0) {
    console.log(`\n📜 Transcript:`);
    console.log(`   Total segments: ${result.transcript.length}`);
    console.log(`\n   First 5 segments:`);
    result.transcript.slice(0, 5).forEach((segment, idx) => {
      console.log(
        `   ${idx + 1}. [${formatTimestamp(segment.start)}] ${segment.text.substring(0, 100)}${segment.text.length > 100 ? "..." : ""}`,
      );
    });

    if (result.transcript.length > 5) {
      console.log(`   ... and ${result.transcript.length - 5} more segments`);
    }
  } else {
    console.log(`\n⚠️  No transcript available for this video`);
  }

  console.log("\n" + "━".repeat(80));
}

async function main() {
  const args = process.argv.slice(2);
  const saveToDbFlag = args.includes("--save-to-db");
  const videoId = args.find((arg) => !arg.startsWith("--"));

  if (!videoId) {
    console.error("❌ Error: Video ID is required");
    console.log("\nUsage: npm run test-transcript <videoId> [--save-to-db]");
    console.log("Example: npm run test-transcript dQw4w9WgXcQ");
    console.log("Example: npm run test-transcript dQw4w9WgXcQ --save-to-db");
    process.exit(1);
  }

  // Validate videoId format (YouTube video IDs are 11 characters)
  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    console.error("❌ Error: Invalid YouTube video ID format");
    console.log("YouTube video IDs should be 11 characters long");
    console.log("Example: dQw4w9WgXcQ");
    process.exit(1);
  }

  try {
    const result = await fetchTranscriptFromApify(videoId);

    if (!result) {
      console.log("\n⚠️  No results found for this video ID");
      process.exit(1);
    }

    displayResults(result);

    if (saveToDbFlag) {
      console.log("\n💾 Saving to database...");
      await saveTranscriptToDb(result);
      console.log("💾 Database save complete!");
    }

    console.log("\n✅ Test completed successfully!\n");
  } catch (error) {
    console.error("\n❌ Test failed:");
    console.error(error);
    process.exit(1);
  }
}

main();
