import { eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import {
  saveTranscriptToDb,
  type TranscriptResult,
} from "@/db/save-transcript";
import { channels, scrapTranscriptV1, videos } from "@/db/schema";

// ============================================================================
// Zod schema for validating Apify API response (snake_case as returned by API)
// ============================================================================

const TranscriptSegmentSchema = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
});

const ApifyTranscriptResponseSchema = z.object({
  video_id: z.string(),
  url: z.string(),
  title: z.string(),
  published_at: z.string(),
  channel_id: z.string(),
  channel_name: z.string(),
  description: z.string(),
  subscriber_count: z.number(),
  view_count: z.number(),
  like_count: z.number(),
  duration_seconds: z.number(),
  is_auto_generated: z.boolean(),
  thumbnail: z.string(),
  transcript: z.array(TranscriptSegmentSchema),
});

// ============================================================================
// Transform snake_case API response to camelCase internal format
// ============================================================================

function transformApifyResponse(
  data: z.infer<typeof ApifyTranscriptResponseSchema>,
): TranscriptResult {
  return {
    id: data.video_id,
    url: data.url,
    title: data.title,
    date: data.published_at,
    channelId: data.channel_id,
    channelName: data.channel_name,
    description: data.description,
    numberOfSubscribers: data.subscriber_count,
    viewCount: data.view_count,
    likes: data.like_count,
    duration: formatDurationFromSeconds(data.duration_seconds),
    isAutoGenerated: data.is_auto_generated,
    thumbnailUrl: data.thumbnail,
    transcript: data.transcript,
  };
}

// Convert seconds to duration string (e.g., "50:20" or "1:23:45")
function formatDurationFromSeconds(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

// ============================================================================
// Step: Check DB for existing transcript
// ============================================================================

export async function stepCheckDbForTranscript(
  videoId: string,
): Promise<TranscriptResult | null> {
  "use step";

  const dbQueryResult = await db
    .select({
      videoId: scrapTranscriptV1.videoId,
      url: videos.url,
      title: videos.title,
      publishedAt: videos.publishedAt,
      channelId: channels.channelId,
      channelName: channels.channelName,
      description: scrapTranscriptV1.description,
      subscriberCount: scrapTranscriptV1.subscriberCount,
      viewCount: scrapTranscriptV1.viewCount,
      likeCount: scrapTranscriptV1.likeCount,
      durationSeconds: scrapTranscriptV1.durationSeconds,
      isAutoGenerated: scrapTranscriptV1.isAutoGenerated,
      thumbnail: scrapTranscriptV1.thumbnail,
      transcript: scrapTranscriptV1.transcript,
    })
    .from(scrapTranscriptV1)
    .innerJoin(videos, eq(scrapTranscriptV1.videoId, videos.videoId))
    .innerJoin(channels, eq(scrapTranscriptV1.channelId, channels.channelId))
    .where(eq(scrapTranscriptV1.videoId, videoId))
    .limit(1);

  if (dbQueryResult.length === 0 || !dbQueryResult[0]) {
    return null;
  }

  const transcriptData = dbQueryResult[0];

  // Validate transcript data with Zod
  if (!transcriptData.transcript || !Array.isArray(transcriptData.transcript)) {
    return null;
  }

  const transcriptParseResult = z
    .array(TranscriptSegmentSchema)
    .safeParse(transcriptData.transcript);

  if (!transcriptParseResult.success) {
    console.error(
      "[DB] Transcript validation failed for video:",
      transcriptData.videoId,
    );
    console.error(
      "[DB] Validation errors:",
      JSON.stringify(transcriptParseResult.error.format(), null, 2),
    );
    return null;
  }

  // Format duration from seconds to string
  const duration =
    transcriptData.durationSeconds !== null
      ? formatDurationFromSeconds(transcriptData.durationSeconds)
      : "0:00";

  return {
    videoId: transcriptData.videoId,
    url: transcriptData.url,
    title: transcriptData.title,
    date: transcriptData.publishedAt
      ? transcriptData.publishedAt.toISOString()
      : "",
    channelId: transcriptData.channelId,
    channelName: transcriptData.channelName,
    description: transcriptData.description ?? "",
    numberOfSubscribers: transcriptData.subscriberCount ?? 0,
    viewCount: transcriptData.viewCount ?? 0,
    likes: transcriptData.likeCount ?? 0,
    duration,
    isAutoGenerated: transcriptData.isAutoGenerated ?? false,
    thumbnailUrl: transcriptData.thumbnail ?? "",
    transcript: transcriptParseResult.data,
  };
}

// ============================================================================
// Step: Fetch from Apify
// ============================================================================

export async function stepFetchFromApify(
  videoId: string,
): Promise<TranscriptResult> {
  "use step";

  const { ApifyClient } = await import("apify-client");

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });
  const actorRun = await client.actor("Uwpce1RSXlrzF6WBA").call({
    youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
  });

  const { items } = await client.dataset(actorRun.defaultDatasetId).listItems();
  const rawApiResponse = items[0];

  if (!rawApiResponse) {
    throw new Error(`No results found for video ID: ${videoId}`);
  }

  // Validate the API response with Zod
  const parseResult = ApifyTranscriptResponseSchema.safeParse(rawApiResponse);

  if (!parseResult.success) {
    console.error(
      "[Apify] Validation failed. Raw response keys:",
      Object.keys(rawApiResponse),
    );
    console.error(
      "[Apify] Validation errors:",
      JSON.stringify(parseResult.error.format(), null, 2),
    );
    throw new Error(
      `Invalid Apify response: ${parseResult.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join(", ")}`,
    );
  }

  // Transform snake_case API response to camelCase
  return transformApifyResponse(parseResult.data);
}

// ============================================================================
// Step: Save to database
// ============================================================================

export async function stepSaveToDb(transcriptData: TranscriptResult) {
  "use step";

  await saveTranscriptToDb(transcriptData);
}
