import { ApifyClient } from "apify-client";
import { db } from "@/db";
import { channels, scrapTranscriptV1, videos } from "@/db/schema";

interface TranscriptResult {
  id: string;
  url: string;
  title: string;
  date?: string;
  channelId: string;
  channelName?: string;
  description?: string;
  numberOfSubscribers?: number;
  viewCount?: number;
  likes?: number;
  duration?: string;
  isAutoGenerated?: boolean;
  thumbnailUrl?: string;
  transcript?: unknown;
}

const parseDuration = (value?: string) => {
  if (!value) return 0;
  const parts = value.split(":").map(Number);
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  return 0;
};

export async function fetchAndStoreTranscriptWorkflow(videoId: string) {
  "use workflow";

  const apifyResult = await stepFetchFromApify(videoId);

  if (!apifyResult) {
    throw new Error(`Apify returned no results for video ID: ${videoId}`);
  }

  await stepSaveToDb(apifyResult);

  return {
    success: true,
    videoId: apifyResult.id,
    title: apifyResult.title,
  };
}

async function stepFetchFromApify(videoId: string) {
  "use step";

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });
  const run = await client.actor("Uwpce1RSXlrzF6WBA").call({
    youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
  });

  const { items } = await client.dataset(run.defaultDatasetId).listItems();
  return (items[0] as TranscriptResult | undefined) ?? null;
}

async function stepSaveToDb(data: TranscriptResult) {
  "use step";

  await db
    .insert(channels)
    .values({
      channelId: data.channelId,
      channelName: data.channelName || "Unknown Channel",
    })
    .onConflictDoUpdate({
      target: channels.channelId,
      set: { channelName: data.channelName },
    });

  await db
    .insert(videos)
    .values({
      videoId: data.id,
      url: data.url,
      title: data.title,
      publishedAt: data.date ? new Date(data.date) : null,
      channelId: data.channelId,
    })
    .onConflictDoUpdate({
      target: videos.videoId,
      set: {
        title: data.title,
        url: data.url,
      },
    });

  await db
    .insert(scrapTranscriptV1)
    .values({
      videoId: data.id,
      channelId: data.channelId,
      description: data.description,
      subscriberCount: data.numberOfSubscribers,
      viewCount: data.viewCount,
      likeCount: data.likes,
      durationSeconds: parseDuration(data.duration),
      isAutoGenerated: data.isAutoGenerated,
      thumbnail: data.thumbnailUrl,
      transcript: data.transcript,
    })
    .onConflictDoUpdate({
      target: scrapTranscriptV1.videoId,
      set: {
        description: data.description,
        subscriberCount: data.numberOfSubscribers,
        viewCount: data.viewCount,
        likeCount: data.likes,
        durationSeconds: parseDuration(data.duration),
        isAutoGenerated: data.isAutoGenerated,
        thumbnail: data.thumbnailUrl,
        transcript: data.transcript,
      },
    });
}
