import { parseDuration } from "@/lib/time-utils";
import { db } from "./index";
import { channels, scrapTranscriptV1, videos } from "./schema";

interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

export interface TranscriptResult {
  videoId: string;
  url: string;
  title: string;
  date: string;
  channelId: string;
  channelName: string;
  description: string;
  numberOfSubscribers: number;
  viewCount: number;
  likes: number;
  duration: string;
  isAutoGenerated: boolean;
  thumbnailUrl: string;
  transcript: TranscriptSegment[];
}

export async function saveTranscriptToDb(data: TranscriptResult) {
  await db
    .insert(channels)
    .values({
      channelId: data.channelId,
      channelName: data.channelName,
    })
    .onConflictDoUpdate({
      target: channels.channelId,
      set: { channelName: data.channelName },
    });

  await db
    .insert(videos)
    .values({
      videoId: data.videoId,
      url: data.url,
      title: data.title,
      publishedAt: data.date ? new Date(data.date) : null,
      channelId: data.channelId,
    })
    .onConflictDoUpdate({
      target: videos.videoId,
      set: {
        title: data.title,
        url: data.url,
      },
    });

  await db
    .insert(scrapTranscriptV1)
    .values({
      videoId: data.videoId,
      channelId: data.channelId,
      description: data.description,
      subscriberCount: data.numberOfSubscribers,
      viewCount: data.viewCount,
      likeCount: data.likes,
      durationSeconds: parseDuration(data.duration),
      isAutoGenerated: data.isAutoGenerated,
      thumbnail: data.thumbnailUrl,
      transcript: data.transcript,
    })
    .onConflictDoUpdate({
      target: scrapTranscriptV1.videoId,
      set: {
        channelId: data.channelId,
        description: data.description,
        subscriberCount: data.numberOfSubscribers,
        viewCount: data.viewCount,
        likeCount: data.likes,
        durationSeconds: parseDuration(data.duration),
        isAutoGenerated: data.isAutoGenerated,
        thumbnail: data.thumbnailUrl,
        transcript: data.transcript,
      },
    });
}
