import { db } from "./index";
import { channels, scrapTranscriptV1, videos } from "./schema";

export interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

export interface TranscriptResult {
  id: string;
  url: string;
  title: string;
  date: string;
  channelId: string;
  channelName: string;
  description: string;
  numberOfSubscribers: number;
  viewCount: number;
  likes: number;
  duration: string;
  isAutoGenerated: boolean;
  thumbnailUrl: string;
  transcript: TranscriptSegment[];
}

export function parseDuration(value?: string): number | null {
  if (!value) return null;

  const parts = value.trim().split(":");
  if (parts.length !== 2 && parts.length !== 3) return null;

  const normalized = parts.map((part) => {
    const numericValue = Number(part);
    if (!Number.isFinite(numericValue) || numericValue < 0) return null;

    const floored = Math.floor(numericValue);
    return Number.isInteger(floored) ? floored : null;
  });

  if (normalized.some((part) => part === null)) return null;

  const [hoursOrMinutes, minutesOrSeconds, seconds] = normalized as number[];

  if (parts.length === 2) {
    return hoursOrMinutes * 60 + minutesOrSeconds;
  }

  return hoursOrMinutes * 3600 + minutesOrSeconds * 60 + seconds;
}

export async function saveTranscriptToDb(data: TranscriptResult) {
  await db
    .insert(channels)
    .values({
      channelId: data.channelId,
      channelName: data.channelName,
    })
    .onConflictDoUpdate({
      target: channels.channelId,
      set: { channelName: data.channelName },
    });

  await db
    .insert(videos)
    .values({
      videoId: data.id,
      url: data.url,
      title: data.title,
      publishedAt: data.date ? new Date(data.date) : null,
      channelId: data.channelId,
    })
    .onConflictDoUpdate({
      target: videos.videoId,
      set: {
        title: data.title,
        url: data.url,
      },
    });

  await db
    .insert(scrapTranscriptV1)
    .values({
      videoId: data.id,
      channelId: data.channelId,
      description: data.description,
      subscriberCount: data.numberOfSubscribers,
      viewCount: data.viewCount,
      likeCount: data.likes,
      durationSeconds: parseDuration(data.duration),
      isAutoGenerated: data.isAutoGenerated,
      thumbnail: data.thumbnailUrl,
      transcript: data.transcript,
    })
    .onConflictDoUpdate({
      target: scrapTranscriptV1.videoId,
      set: {
        channelId: data.channelId,
        description: data.description,
        subscriberCount: data.numberOfSubscribers,
        viewCount: data.viewCount,
        likeCount: data.likes,
        durationSeconds: parseDuration(data.duration),
        isAutoGenerated: data.isAutoGenerated,
        thumbnail: data.thumbnailUrl,
        transcript: data.transcript,
      },
    });
}
