import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  serial,
  text,
  timestamp,
  unique,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

// ============================================================================
// Enums
// ============================================================================

export const extractionStatusEnum = pgEnum("extraction_status", [
  "pending",
  "in_progress",
  "completed",
  "failed",
]);

export type ExtractionStatus = (typeof extractionStatusEnum.enumValues)[number];

export const analysisStatusEnum = pgEnum("analysis_status", [
  "pending",
  "streaming",
  "completed",
  "failed",
]);

export type AnalysisStatus = (typeof analysisStatusEnum.enumValues)[number];

export const framePositionEnum = pgEnum("frame_position", ["first", "last"]);

export type FramePosition = (typeof framePositionEnum.enumValues)[number];

export const samenessEnum = pgEnum("sameness", ["same", "different"]);

export type Sameness = (typeof samenessEnum.enumValues)[number];

// ============================================================================
// Core Video Tables
// ============================================================================

export const channels = pgTable("channels", {
  channelId: varchar("channel_id", { length: 64 }).primaryKey(),
  channelName: text("channel_name").notNull(),
});

export const videos = pgTable(
  "videos",
  {
    videoId: varchar("video_id", { length: 32 }).primaryKey(),
    url: text("url").notNull(),
    title: text("title").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    channelId: varchar("channel_id", { length: 64 })
      .notNull()
      .references(() => channels.channelId, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
  },
  (table) => [index("videos_channel_id_idx").on(table.channelId)],
);

export const scrapTranscriptV1 = pgTable(
  "scrap_transcript_v1",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    channelId: varchar("channel_id", { length: 64 })
      .notNull()
      .references(() => channels.channelId, { onDelete: "cascade" }),
    description: text("description"),
    subscriberCount: integer("subscriber_count"),
    viewCount: integer("view_count"),
    likeCount: integer("like_count"),
    durationSeconds: integer("duration_seconds"),
    isAutoGenerated: boolean("is_auto_generated"),
    thumbnail: text("thumbnail"),
    transcript: jsonb("transcript"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [unique("unique_video_transcript").on(table.videoId)],
);

export type ScrapedTranscript = typeof scrapTranscriptV1.$inferSelect;
export type NewScrapedTranscript = typeof scrapTranscriptV1.$inferInsert;

export const videoAnalysisRuns = pgTable("video_analysis_runs", {
  videoId: varchar("video_id", { length: 32 })
    .notNull()
    .primaryKey()
    .references(() => videos.videoId, { onDelete: "cascade" }),
  result: jsonb("result").$type<Record<string, unknown>>(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type VideoAnalysisRun = typeof videoAnalysisRuns.$inferSelect;
export type NewVideoAnalysisRun = typeof videoAnalysisRuns.$inferInsert;

export const videoAnalysisWorkflowIds = pgTable(
  "video_analysis_workflow_ids",
  {
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .primaryKey()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    workflowId: varchar("workflow_id", { length: 100 }).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_analysis_workflow_ids_video_id_idx").on(table.workflowId),
  ],
);

export type VideoAnalysisWorkflowId =
  typeof videoAnalysisWorkflowIds.$inferSelect;
export type NewVideoAnalysisWorkflowId =
  typeof videoAnalysisWorkflowIds.$inferInsert;

// ============================================================================
// Slides Tables
// ============================================================================

export const videoSlideExtractions = pgTable(
  "video_slide_extractions",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    status: extractionStatusEnum("status").notNull().default("pending"),
    runId: varchar("run_id", { length: 100 }), // Workflow run ID for resumption
    totalSlides: integer("total_slides"),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_slide_extractions_video_idx").on(table.videoId),
    unique("video_slide_extractions_video_unique").on(table.videoId),
  ],
);

export type VideoSlideExtraction = typeof videoSlideExtractions.$inferSelect;

export const videoSlides = pgTable(
  "video_slides",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    slideNumber: integer("slide_index").notNull(),

    // Timing
    startTime: real("start_time").notNull(), // seconds with floating point precision
    endTime: real("end_time").notNull(),
    duration: real("duration").notNull(),

    // First frame data
    firstFrameImageUrl: text("first_frame_image_url"),
    firstFrameIsDuplicate: boolean("first_frame_is_duplicate")
      .default(false)
      .notNull(),
    firstFrameDuplicateOfSlideNumber: integer(
      "first_frame_duplicate_of_segment_id",
    ),
    firstFrameDuplicateOfFramePosition: framePositionEnum(
      "first_frame_duplicate_of_frame_position",
    ),

    // Last frame data
    lastFrameImageUrl: text("last_frame_image_url"),
    lastFrameIsDuplicate: boolean("last_frame_is_duplicate")
      .default(false)
      .notNull(),
    lastFrameDuplicateOfSlideNumber: integer(
      "last_frame_duplicate_of_segment_id",
    ),
    lastFrameDuplicateOfFramePosition: framePositionEnum(
      "last_frame_duplicate_of_frame_position",
    ),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_slides_video_idx").on(table.videoId),
    unique("video_slides_video_index").on(table.videoId, table.slideNumber),
  ],
);

export type VideoSlide = typeof videoSlides.$inferSelect;
export type NewVideoSlide = typeof videoSlides.$inferInsert;

/**
 * Feedback on individual slides - validation of frame annotations and sameness
 */
export const slideFeedback = pgTable(
  "slide_feedback",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    slideNumber: integer("slide_index").notNull(),

    // First frame validation
    firstFrameIsDuplicateValidated: boolean(
      "first_frame_is_duplicate_validated",
    ),

    // Last frame validation
    lastFrameIsDuplicateValidated: boolean("last_frame_is_duplicate_validated"),

    // Sameness feedback
    framesSameness: samenessEnum("frames_sameness"),

    // Frame selection - whether individual frames are picked for export
    isFirstFramePicked: boolean("is_first_frame_picked")
      .default(true)
      .notNull(),
    isLastFramePicked: boolean("is_last_frame_picked").default(true).notNull(),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("slide_feedback_video_idx").on(table.videoId),
    unique("slide_feedback_video_slide").on(table.videoId, table.slideNumber),
  ],
);

export type SlideFeedback = typeof slideFeedback.$inferSelect;
export type NewSlideFeedback = typeof slideFeedback.$inferInsert;

// ============================================================================
// External Transcript Tables
// ============================================================================

/**
 * External transcripts - pasted by users directly (not from YouTube)
 */
export const externalTranscripts = pgTable(
  "external_transcripts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    title: text("title").notNull(),
    description: text("description"),
    source: text("source"), // Freeform text (e.g., "Podcast episode 123")
    author: text("author"), // Similar to channelName for YouTube
    additional_comments: text("additional_comments"), // For future AI processing
    transcript_text: text("transcript_text").notNull(), // Plain text transcript
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [index("external_transcripts_created_at_idx").on(table.createdAt)],
);

export type ExternalTranscript = typeof externalTranscripts.$inferSelect;
export type NewExternalTranscript = typeof externalTranscripts.$inferInsert;

/**
 * Analysis runs for external transcripts - stores AI output with versioning
 */
export const externalTranscriptAnalysisRuns = pgTable(
  "external_transcript_analysis_runs",
  {
    id: serial("id").primaryKey(),
    transcriptId: uuid("transcript_id")
      .notNull()
      .references(() => externalTranscripts.id, { onDelete: "cascade" }),
    version: integer("version").notNull().default(1),

    // Workflow run ID for stream resumption
    workflowRunId: varchar("workflow_run_id", { length: 100 }),

    // AI analysis output - unified JSONB column
    result: jsonb("result").$type<Record<string, unknown>>(),

    // Context for rerolls - what instructions led to this version
    additionalInstructions: text("additional_instructions"),

    status: analysisStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("external_transcript_analysis_runs_transcript_idx").on(
      table.transcriptId,
    ),
    unique("external_transcript_analysis_runs_version").on(
      table.transcriptId,
      table.version,
    ),
  ],
);

export type ExternalTranscriptAnalysisRun =
  typeof externalTranscriptAnalysisRuns.$inferSelect;
export type NewExternalTranscriptAnalysisRun =
  typeof externalTranscriptAnalysisRuns.$inferInsert;
