import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
  varchar,
} from "drizzle-orm/pg-core";

// ============================================================================
// Enums
// ============================================================================

export const extractionStatusEnum = pgEnum("extraction_status", [
  "pending",
  "in_progress",
  "completed",
  "failed",
]);

export type ExtractionStatus = (typeof extractionStatusEnum.enumValues)[number];

export const analysisStatusEnum = pgEnum("analysis_status", [
  "pending",
  "streaming",
  "completed",
  "failed",
]);

export type AnalysisStatus = (typeof analysisStatusEnum.enumValues)[number];

// ============================================================================
// Core Video Tables
// ============================================================================

export const channels = pgTable("channels", {
  channelId: varchar("channel_id", { length: 64 }).primaryKey(),
  channelName: text("channel_name").notNull(),
});

export const videos = pgTable(
  "videos",
  {
    videoId: varchar("video_id", { length: 32 }).primaryKey(),
    url: text("url").notNull(),
    title: text("title").notNull(),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    channelId: varchar("channel_id", { length: 64 })
      .notNull()
      .references(() => channels.channelId, {
        onDelete: "cascade",
        onUpdate: "cascade",
      }),
  },
  (table) => [index("videos_channel_id_idx").on(table.channelId)],
);

export const scrapTranscriptV1 = pgTable(
  "scrap_transcript_v1",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    channelId: varchar("channel_id", { length: 64 })
      .notNull()
      .references(() => channels.channelId, { onDelete: "cascade" }),
    description: text("description"),
    subscriberCount: integer("subscriber_count"),
    viewCount: integer("view_count"),
    likeCount: integer("like_count"),
    durationSeconds: integer("duration_seconds"),
    isAutoGenerated: boolean("is_auto_generated"),
    thumbnail: text("thumbnail"),
    transcript: jsonb("transcript"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => [unique("unique_video_transcript").on(table.videoId)],
);

/**
 * A god prompt run - stores the complete AI output as JSONB
 * Each run is a version for a specific video
 */
export const videoAnalysisRuns = pgTable(
  "video_analysis_runs",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    version: integer("version").notNull().default(1),

    // God prompt output - unified JSONB column
    result: jsonb("result").$type<Record<string, unknown>>(),

    // Context for rerolls - what instructions led to this version
    additionalInstructions: text("additional_instructions"),

    status: analysisStatusEnum("status").notNull().default("pending"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_analysis_runs_video_idx").on(table.videoId),
    unique("video_analysis_runs_version").on(table.videoId, table.version),
  ],
);

export type VideoAnalysisRun = typeof videoAnalysisRuns.$inferSelect;
export type NewVideoAnalysisRun = typeof videoAnalysisRuns.$inferInsert;

/**
 * Feedback on individual sections
 */
export const sectionFeedback = pgTable(
  "section_feedback",
  {
    id: serial("id").primaryKey(),
    runId: integer("run_id")
      .notNull()
      .references(() => videoAnalysisRuns.id, { onDelete: "cascade" }),
    sectionKey: varchar("section_key", { length: 128 }).notNull(),

    // Feedback
    rating: varchar("rating", { length: 16 }), // "useful" | "not_useful"
    comment: text("comment"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("section_feedback_run_idx").on(table.runId)],
);

export type SectionFeedback = typeof sectionFeedback.$inferSelect;
export type NewSectionFeedback = typeof sectionFeedback.$inferInsert;

/**
 * Overall run feedback / preference
 */
export const runFeedback = pgTable("run_feedback", {
  id: serial("id").primaryKey(),
  runId: integer("run_id")
    .notNull()
    .references(() => videoAnalysisRuns.id, { onDelete: "cascade" }),
  overallRating: integer("overall_rating"), // 1-5 scale
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export type RunFeedback = typeof runFeedback.$inferSelect;
export type NewRunFeedback = typeof runFeedback.$inferInsert;

// ============================================================================
// Slides Tables
// ============================================================================

export const videoSlideExtractions = pgTable(
  "video_slide_extractions",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    status: extractionStatusEnum("status").notNull().default("pending"),
    runId: varchar("run_id", { length: 100 }), // Workflow run ID for resumption
    totalSlides: integer("total_slides"),
    errorMessage: text("error_message"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_slide_extractions_video_idx").on(table.videoId),
    unique("video_slide_extractions_video_unique").on(table.videoId),
  ],
);

export type VideoSlideExtraction = typeof videoSlideExtractions.$inferSelect;

export const videoSlides = pgTable(
  "video_slides",
  {
    id: serial("id").primaryKey(),
    videoId: varchar("video_id", { length: 32 })
      .notNull()
      .references(() => videos.videoId, { onDelete: "cascade" }),
    slideIndex: integer("slide_index").notNull(),
    frameId: varchar("frame_id", { length: 100 }),

    // Timing
    startTime: integer("start_time").notNull(), // seconds
    endTime: integer("end_time").notNull(),
    duration: integer("duration").notNull(),

    // S3 reference (we store URI, not blob URL)
    s3Uri: text("s3_uri"),
    s3Bucket: varchar("s3_bucket", { length: 100 }),
    s3Key: text("s3_key"),

    // Text detection metadata
    hasText: boolean("has_text").default(false),
    textConfidence: integer("text_confidence"), // 0-100
    textBoxCount: integer("text_box_count"),

    // Deduplication
    isDuplicate: boolean("is_duplicate").default(false),
    duplicateOfSegmentId: integer("duplicate_of_segment_id"),

    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("video_slides_video_idx").on(table.videoId),
    unique("video_slides_video_index").on(table.videoId, table.slideIndex),
  ],
);

export type VideoSlide = typeof videoSlides.$inferSelect;
export type NewVideoSlide = typeof videoSlides.$inferInsert;
