#!/usr/bin/env tsx

/**
 * CLI script to test the fetch transcript functionality
 * Usage: npm run test-transcript <videoId>
 * Example: npm run test-transcript dQw4w9WgXcQ
 */

import { ApifyClient } from "apify-client";
import * as dotenv from "dotenv";

// Load environment variables
dotenv.config({ path: ".env.local" });
dotenv.config();

interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

interface TranscriptResult {
  id: string;
  url: string;
  title: string;
  date?: string;
  channelId: string;
  channelName?: string;
  description?: string;
  numberOfSubscribers?: number;
  viewCount?: number;
  likes?: number;
  duration?: string;
  isAutoGenerated?: boolean;
  thumbnailUrl?: string;
  transcript?: TranscriptSegment[];
}

async function fetchTranscriptFromApify(
  videoId: string,
): Promise<TranscriptResult | null> {
  if (!process.env.APIFY_API_TOKEN) {
    throw new Error(
      "APIFY_API_TOKEN is not defined. Please set it in your .env.local file",
    );
  }

  console.log(`\n🔍 Fetching transcript for video ID: ${videoId}`);
  console.log(`📡 Using Apify API...\n`);

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });

  try {
    const run = await client.actor("Uwpce1RSXlrzF6WBA").call({
      youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
    });

    console.log(`✅ Apify run completed: ${run.id}`);

    const { items } = await client.dataset(run.defaultDatasetId).listItems();
    return (items[0] as unknown as TranscriptResult | undefined) ?? null;
  } catch (error) {
    console.error("❌ Error fetching transcript:", error);
    throw error;
  }
}

function formatTimestamp(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function displayResults(result: TranscriptResult) {
  console.log("\n📊 RESULTS:");
  console.log("━".repeat(80));
  console.log(`\n📹 Video Information:`);
  console.log(`   ID: ${result.id}`);
  console.log(`   Title: ${result.title}`);
  console.log(`   URL: ${result.url}`);
  console.log(
    `   Channel: ${result.channelName || "Unknown"} (${result.channelId})`,
  );
  console.log(`   Published: ${result.date || "Unknown"}`);
  console.log(`   Duration: ${result.duration || "Unknown"}`);
  console.log(`   Views: ${result.viewCount?.toLocaleString() || "Unknown"}`);
  console.log(`   Likes: ${result.likes?.toLocaleString() || "Unknown"}`);
  console.log(
    `   Subscribers: ${result.numberOfSubscribers?.toLocaleString() || "Unknown"}`,
  );
  console.log(`   Auto-generated: ${result.isAutoGenerated ? "Yes" : "No"}`);

  if (result.description) {
    console.log(`\n📝 Description:`);
    console.log(
      `   ${result.description.substring(0, 200)}${result.description.length > 200 ? "..." : ""}`,
    );
  }

  if (result.transcript && result.transcript.length > 0) {
    console.log(`\n📜 Transcript:`);
    console.log(`   Total segments: ${result.transcript.length}`);
    console.log(`\n   First 5 segments:`);
    result.transcript.slice(0, 5).forEach((segment, idx) => {
      console.log(
        `   ${idx + 1}. [${formatTimestamp(segment.start)}] ${segment.text.substring(0, 100)}${segment.text.length > 100 ? "..." : ""}`,
      );
    });

    if (result.transcript.length > 5) {
      console.log(`   ... and ${result.transcript.length - 5} more segments`);
    }
  } else {
    console.log(`\n⚠️  No transcript available for this video`);
  }

  console.log("\n" + "━".repeat(80));
}

async function main() {
  const videoId = process.argv[2];

  if (!videoId) {
    console.error("❌ Error: Video ID is required");
    console.log("\nUsage: npm run test-transcript <videoId>");
    console.log("Example: npm run test-transcript dQw4w9WgXcQ");
    process.exit(1);
  }

  // Validate videoId format (YouTube video IDs are 11 characters)
  if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
    console.error("❌ Error: Invalid YouTube video ID format");
    console.log("YouTube video IDs should be 11 characters long");
    console.log("Example: dQw4w9WgXcQ");
    process.exit(1);
  }

  try {
    const result = await fetchTranscriptFromApify(videoId);

    if (!result) {
      console.log("\n⚠️  No results found for this video ID");
      process.exit(1);
    }

    displayResults(result);

    console.log("\n✅ Test completed successfully!\n");
  } catch (error) {
    console.error("\n❌ Test failed:");
    console.error(error);
    process.exit(1);
  }
}

main();
