"use client"

import { Streamdown } from "streamdown"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"

export default function VideoAnalysisPage() {
  const [markdown, setMarkdown] = useState("")
  const [isStreaming, setIsStreaming] = useState(false)

  const fullMarkdown = `# Video Analysis Report

## Executive Summary

This is a **comprehensive analysis** of the video content using AI-powered streaming markdown.

### Key Findings

1. **Content Quality**: High-quality video with clear audio
2. **Topic Coverage**: Comprehensive coverage of the subject matter
3. **Engagement Metrics**: Strong viewer retention throughout

## Detailed Analysis

### Introduction Section

The video begins with a compelling hook that captures attention within the first \`30 seconds\`. The presenter demonstrates:

- Clear communication style
- Strong subject matter expertise
- Engaging visual aids

### Main Content

The core content is divided into several segments:

\`\`\`javascript
// Example code snippet from the video
function analyzeVideo(url) {
  const transcript = extractTranscript(url);
  const insights = generateInsights(transcript);
  return insights;
}
\`\`\`

### Mathematical Concepts

Some key formulas discussed:

$$E = mc^2$$

$$\\sum_{i=1}^{n} x_i = x_1 + x_2 + ... + x_n$$

### Data Visualization

\`\`\`mermaid
graph TD
    A[Video Input] --> B{Processing}
    B -->|Transcript| C[Text Analysis]
    B -->|Audio| D[Sound Analysis]
    B -->|Visual| E[Frame Analysis]
    C --> F[Generate Report]
    D --> F
    E --> F
    F --> G[Final Output]
\`\`\`

### Comparison Table

| Metric | Score | Benchmark |
|--------|-------|-----------|
| Audio Quality | 9.5/10 | 8.0/10 |
| Visual Clarity | 9.0/10 | 7.5/10 |
| Content Depth | 8.8/10 | 8.2/10 |
| Engagement | 9.2/10 | 7.8/10 |

## Recommendations

> 💡 **Pro Tip**: Consider adding more visual examples to enhance understanding of complex concepts.

### Action Items

- [ ] Add chapter markers for better navigation
- [ ] Include supplementary resources in description
- [x] Optimize audio levels for consistency
- [x] Add subtitles for accessibility

### Code Examples

Here's a more detailed implementation:

\`\`\`typescript
interface VideoMetadata {
  title: string;
  duration: number;
  views: number;
  uploadDate: Date;
}

async function processVideo(metadata: VideoMetadata) {
  const analysis = {
    title: metadata.title,
    duration: formatDuration(metadata.duration),
    engagement: calculateEngagement(metadata.views),
  };
  
  return analysis;
}
\`\`\`

## Conclusion

This video demonstrates **excellent production quality** and provides valuable insights. The combination of clear explanations, supporting visuals, and practical examples makes it highly effective for its target audience.

---

*Generated by Video2MD Analysis Engine*
  `

  useEffect(() => {
    if (!isStreaming) return

    setMarkdown("")
    let currentIndex = 0

    const interval = setInterval(() => {
      if (currentIndex < fullMarkdown.length) {
        setMarkdown((prev) => prev + fullMarkdown[currentIndex])
        currentIndex++
      } else {
        setIsStreaming(false)
        clearInterval(interval)
      }
    }, 10) // Stream at ~100 characters per second

    return () => clearInterval(interval)
  }, [isStreaming, fullMarkdown])

  const handleStartStream = () => {
    setIsStreaming(true)
  }

  const handleReset = () => {
    setMarkdown("")
    setIsStreaming(false)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-muted/20">
      <div className="container mx-auto px-4 py-12 max-w-5xl">
        <div className="mb-8">
          <h1 className="text-4xl font-bold tracking-tight mb-3 text-balance">Video Analysis</h1>
          <p className="text-muted-foreground text-lg">Streaming markdown analysis powered by Streamdown</p>
        </div>

        <div className="flex gap-3 mb-6">
          <Button onClick={handleStartStream} disabled={isStreaming || markdown.length > 0}>
            {isStreaming ? "Streaming..." : "Start Stream"}
          </Button>
          <Button onClick={handleReset} variant="outline" disabled={isStreaming}>
            Reset
          </Button>
        </div>

        <Card className="border-2 shadow-lg">
          <CardHeader>
            <CardTitle className="text-2xl">Analysis Report</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-slate dark:prose-invert max-w-none">
            <Streamdown>{markdown}</Streamdown>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
