import { eq } from "drizzle-orm";
import { getWritable } from "workflow";
import { z } from "zod";
import { db } from "@/db";
import {
  saveTranscriptToDb,
  type TranscriptResult,
} from "@/db/save-transcript";
import { channels, scrapTranscriptV1, videos } from "@/db/schema";

// Re-export for consumers
export type { TranscriptResult };

// ============================================================================
// Stream Event Types
// ============================================================================

export type TranscriptStreamEvent =
  | { type: "progress"; progress: number; message: string }
  | { type: "complete"; video: { title: string; channelName: string } }
  | { type: "error"; error: string };

// ============================================================================
// Stream Emitters
// ============================================================================

export async function emitProgress(progress: number, message: string) {
  "use step";

  const writable = getWritable<TranscriptStreamEvent>();
  const writer = writable.getWriter();
  await writer.write({ type: "progress", progress, message });
  writer.releaseLock();
}

export async function emitComplete(video: {
  title: string;
  channelName: string;
}) {
  "use step";

  const writable = getWritable<TranscriptStreamEvent>();
  const writer = writable.getWriter();
  await writer.write({ type: "complete", video });
  writer.releaseLock();
  await writable.close();
}

export async function emitError(error: string) {
  "use step";

  const writable = getWritable<TranscriptStreamEvent>();
  const writer = writable.getWriter();
  await writer.write({ type: "error", error });
  writer.releaseLock();
  await writable.close();
}

// ============================================================================
// Schemas
// ============================================================================

const TranscriptSegmentSchema = z.object({
  start: z.number(),
  end: z.number(),
  text: z.string(),
});

const ApifyTranscriptResponseSchema = z.object({
  video_id: z.string(),
  url: z.string(),
  title: z.string(),
  published_at: z.string(),
  channel_id: z.string(),
  channel_name: z.string(),
  description: z.string(),
  subscriber_count: z.number(),
  view_count: z.number(),
  like_count: z.number(),
  duration_seconds: z.number(),
  is_auto_generated: z.boolean(),
  thumbnail: z.string(),
  transcript: z.array(TranscriptSegmentSchema),
});

// ============================================================================
// Helpers
// ============================================================================

function formatDurationFromSeconds(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

function transformApifyResponse(
  data: z.infer<typeof ApifyTranscriptResponseSchema>,
): TranscriptResult {
  return {
    id: data.video_id,
    url: data.url,
    title: data.title,
    date: data.published_at,
    channelId: data.channel_id,
    channelName: data.channel_name,
    description: data.description,
    numberOfSubscribers: data.subscriber_count,
    viewCount: data.view_count,
    likes: data.like_count,
    duration: formatDurationFromSeconds(data.duration_seconds),
    isAutoGenerated: data.is_auto_generated,
    thumbnailUrl: data.thumbnail,
    transcript: data.transcript,
  };
}

// ============================================================================
// Step: Check DB for existing transcript
// ============================================================================

export async function stepCheckDbForTranscript(
  videoId: string,
): Promise<TranscriptResult | null> {
  "use step";

  const result = await db
    .select({
      videoId: scrapTranscriptV1.videoId,
      url: videos.url,
      title: videos.title,
      publishedAt: videos.publishedAt,
      channelId: channels.channelId,
      channelName: channels.channelName,
      description: scrapTranscriptV1.description,
      subscriberCount: scrapTranscriptV1.subscriberCount,
      viewCount: scrapTranscriptV1.viewCount,
      likeCount: scrapTranscriptV1.likeCount,
      durationSeconds: scrapTranscriptV1.durationSeconds,
      isAutoGenerated: scrapTranscriptV1.isAutoGenerated,
      thumbnail: scrapTranscriptV1.thumbnail,
      transcript: scrapTranscriptV1.transcript,
    })
    .from(scrapTranscriptV1)
    .innerJoin(videos, eq(scrapTranscriptV1.videoId, videos.videoId))
    .innerJoin(channels, eq(scrapTranscriptV1.channelId, channels.channelId))
    .where(eq(scrapTranscriptV1.videoId, videoId))
    .limit(1);

  if (result.length === 0 || !result[0]) {
    return null;
  }

  const data = result[0];

  if (!data.transcript || !Array.isArray(data.transcript)) {
    return null;
  }

  const transcriptParseResult = z
    .array(TranscriptSegmentSchema)
    .safeParse(data.transcript);

  if (!transcriptParseResult.success) {
    console.error("[DB] Transcript validation failed for video:", data.videoId);
    return null;
  }

  const duration =
    data.durationSeconds !== null
      ? formatDurationFromSeconds(data.durationSeconds)
      : "0:00";

  return {
    id: data.videoId,
    url: data.url,
    title: data.title,
    date: data.publishedAt ? data.publishedAt.toISOString() : "",
    channelId: data.channelId,
    channelName: data.channelName,
    description: data.description ?? "",
    numberOfSubscribers: data.subscriberCount ?? 0,
    viewCount: data.viewCount ?? 0,
    likes: data.likeCount ?? 0,
    duration,
    isAutoGenerated: data.isAutoGenerated ?? false,
    thumbnailUrl: data.thumbnail ?? "",
    transcript: transcriptParseResult.data,
  };
}

// ============================================================================
// Step: Fetch from Apify
// ============================================================================

export async function stepFetchFromApify(
  videoId: string,
): Promise<TranscriptResult | null> {
  "use step";

  const { ApifyClient } = await import("apify-client");

  if (!process.env.APIFY_API_TOKEN) {
    throw new Error("APIFY_API_TOKEN is not defined");
  }

  const client = new ApifyClient({ token: process.env.APIFY_API_TOKEN });
  const run = await client.actor("Uwpce1RSXlrzF6WBA").call({
    youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
  });

  const { items } = await client.dataset(run.defaultDatasetId).listItems();
  const rawResult = items[0];

  if (!rawResult) {
    return null;
  }

  const parseResult = ApifyTranscriptResponseSchema.safeParse(rawResult);

  if (!parseResult.success) {
    console.error(
      "[Apify] Validation failed. Raw response keys:",
      Object.keys(rawResult),
    );
    throw new Error(
      `Invalid Apify response: ${parseResult.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join(", ")}`,
    );
  }

  return transformApifyResponse(parseResult.data);
}

// ============================================================================
// Step: Save to database
// ============================================================================

export async function stepSaveToDb(data: TranscriptResult) {
  "use step";

  await saveTranscriptToDb(data);
}
